name: friends_run
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  google_maps_flutter: ^2.12.1
  flutter_google_maps_webservices: ^1.1.1
  flutter_polyline_points: ^2.1.0
  location: ^8.0.0
  syncfusion_flutter_gauges: ^29.1.37
  geolocator: ^13.0.4
  http: ^1.3.0
  meta: ^1.16.0
  geocoding: ^3.0.0
  google_places_autocomplete_text_field: ^1.1.0
  google_api_headers: ^4.4.3
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
